// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppBuildTime() {
  return window['go']['app']['App']['AppBuildTime']();
}

export function AppVersion() {
  return window['go']['app']['App']['AppVersion']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function OllamaHost() {
  return window['go']['app']['App']['OllamaHost']();
}
