// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ollama} from '../models';
import {api} from '../models';
import {app} from '../models';

export function AppInfo():Promise<{[key: string]: string}>;

export function OllamaChat(arg1:ollama.ChatRequest,arg2:api.ChatResponseFunc):Promise<void>;

export function OllamaDelete(arg1:string):Promise<void>;

export function OllamaEmbed(arg1:ollama.EmbedRequest):Promise<ollama.EmbedResponse>;

export function OllamaEmbeddings(arg1:ollama.EmbeddingRequest):Promise<ollama.EmbeddingResponse>;

export function OllamaEnvs():Promise<Array<app.OllamaEnvVar>>;

export function OllamaGenerate(arg1:ollama.GenerateRequest,arg2:api.GenerateResponseFunc):Promise<void>;

export function OllamaHeartbeat():Promise<void>;

export function OllamaHost():Promise<string>;

export function OllamaList():Promise<ollama.ListResponse>;

export function OllamaListRunning():Promise<ollama.ProcessResponse>;

export function OllamaPull(arg1:string):Promise<void>;

export function OllamaShow(arg1:ollama.ShowRequest):Promise<ollama.ShowResponse>;

export function OllamaVersion():Promise<string>;

export function StartOllama():Promise<void>;
