// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppBuildTime():Promise<string>;

export function AppVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OllamaHost():Promise<string>;
