// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {ollama} from '../models';

export function AppInfo():Promise<{[key: string]: string}>;

export function OllamaEnvs():Promise<Array<app.OllamaEnvVar>>;

export function OllamaHeartbeat():Promise<void>;

export function OllamaHost():Promise<string>;

export function OllamaList():Promise<ollama.ListResponse>;

export function OllamaListRunning():Promise<ollama.ProcessResponse>;

export function OllamaVersion():Promise<string>;

export function StartOllama():Promise<void>;
