// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Conversation(arg1:string):Promise<app.ConversationResponse>;

export function CreateSession(arg1:string):Promise<app.SessionModel>;

export function DeleteSession(arg1:string):Promise<string>;

export function GetSession(arg1:string):Promise<app.SessionModel>;

export function SessionHistoryMessages(arg1:string):Promise<Array<app.ChatMessage>>;

export function Sessions():Promise<Array<app.SessionModel>>;
