// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function OllamaConfigs():Promise<app.OllamaConfig>;

export function ProxyConfigs():Promise<app.ProxyConfig>;

export function SaveOllamaConfigs(arg1:app.OllamaConfig):Promise<void>;

export function SaveProxyConfigs(arg1:app.ProxyConfig):Promise<void>;
