// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OllamaConfigs() {
  return window['go']['app']['Config']['OllamaConfigs']();
}

export function ProxyConfigs() {
  return window['go']['app']['Config']['ProxyConfigs']();
}

export function SaveOllamaConfigs(arg1) {
  return window['go']['app']['Config']['SaveOllamaConfigs'](arg1);
}

export function SaveProxyConfigs(arg1) {
  return window['go']['app']['Config']['SaveProxyConfigs'](arg1);
}
