// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateSession(arg1:string):Promise<app.Session>;

export function DeleteSession(arg1:string):Promise<app.Session>;

export function Sessions(arg1:boolean):Promise<Array<app.Session>>;
