// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['DownLoader']['Cancel'](arg1);
}

export function List() {
  return window['go']['app']['DownLoader']['List']();
}

export function Pull(arg1) {
  return window['go']['app']['DownLoader']['Pull'](arg1);
}
