// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function List():Promise<Array<app.DownloadItem>>;

export function Pull(arg1:string):Promise<void>;
