// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ollama} from '../models';
import {app} from '../models';

export function Chat(arg1:string,arg2:string):Promise<void>;

export function Copy(arg1:string):Promise<void>;

export function Create(arg1:string,arg2:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function Embed(arg1:string):Promise<ollama.EmbedResponse>;

export function Embeddings(arg1:string):Promise<ollama.EmbeddingResponse>;

export function Envs():Promise<Array<app.OllamaEnvVar>>;

export function Generate(arg1:string,arg2:string):Promise<void>;

export function Heartbeat():Promise<void>;

export function Host():Promise<string>;

export function LibraryOnline(arg1:string):Promise<Array<ollama.ModelInfo>>;

export function List():Promise<ollama.ListResponse>;

export function ListRunning():Promise<ollama.ProcessResponse>;

export function ModelInfoOnline(arg1:string):Promise<ollama.ModelInfoResponse>;

export function Pull(arg1:string,arg2:string):Promise<void>;

export function Push(arg1:string,arg2:string):Promise<void>;

export function SearchOnline(arg1:string):Promise<ollama.SearchResponse>;

export function Show(arg1:string):Promise<ollama.ShowResponse>;

export function Start():Promise<void>;

export function Version():Promise<string>;
