// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['app']['Ollama']['Delete'](arg1);
}

export function Embeddings(arg1) {
  return window['go']['app']['Ollama']['Embeddings'](arg1);
}

export function Envs() {
  return window['go']['app']['Ollama']['Envs']();
}

export function Heartbeat() {
  return window['go']['app']['Ollama']['Heartbeat']();
}

export function LibraryOnline(arg1) {
  return window['go']['app']['Ollama']['LibraryOnline'](arg1);
}

export function List() {
  return window['go']['app']['Ollama']['List']();
}

export function ListRunning() {
  return window['go']['app']['Ollama']['ListRunning']();
}

export function ModelInfoOnline(arg1) {
  return window['go']['app']['Ollama']['ModelInfoOnline'](arg1);
}

export function Pull(arg1, arg2) {
  return window['go']['app']['Ollama']['Pull'](arg1, arg2);
}

export function SearchOnline(arg1) {
  return window['go']['app']['Ollama']['SearchOnline'](arg1);
}

export function Show(arg1) {
  return window['go']['app']['Ollama']['Show'](arg1);
}

export function Start() {
  return window['go']['app']['Ollama']['Start']();
}

export function Version() {
  return window['go']['app']['Ollama']['Version']();
}
