name: ollama-desktop package build

on:
  # push:
  #   tags:
      # Match any new tag
  #     - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'ollama-desktop'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'ollama-desktop'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'ollama-desktop'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: jianggujin/ollama-desktop@master
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.20'
          node-version: '18.12.1'
          wails-build-arg: -ldflags "-s -w -X 'ollama-desktop/internal/config.BuildHash=${{ github.sha }}' -X 'ollama-desktop/internal/config.BuildVersion=V0.0.1'" -trimpath